version: "3"
services:
  db:
    container_name: database
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    restart: always

  cron:
    container_name: cron
    depends_on:
      - db
    build: cron/.
    restart: always

  website:
    container_name: website
    depends_on:
      - db
    build: website/.
    ports:
      - "80:80"
    restart: always

  # nginx:
  #   container_name: nginx
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   restart: always
  #   volumes:
  #     - ./Data/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./Data/nginx/:/var/log/nginx/log/