version: "3"
services:
  cron:
    container_name: cron
    build: cron/.
    restart: always
    volumes:
      - ./cron/cron.log:/logs/cron.log

  db:
    container_name: database
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    restart: always

  # nginx:
  #   container_name: nginx
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   restart: always
  #   volumes:
  #     - ./Data/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./Data/nginx/:/var/log/nginx/log/